Module TwitterUrls

    Public Const TWITTER_OAUTH_REQUEST_TOKEN_URL As String = "https://api.twitter.com/oauth/request_token"
    Public Const TWITTER_OAUTH_ACCESS_TOKEN_REQUEST_URL As String = "https://api.twitter.com/oauth/access_token"
    Public Const TWITTER_UPDATE_STATUS_URL As String = "https://api.twitter.com/1.1/statuses/update.json"
    Public Const TWITTER_GET_TIMELINE_URL As String = "https://api.twitter.com/1.1/statuses/user_timeline.json"
    Public Const TWITTER_SHOWUSER_URL As String = "https://api.twitter.com/1.1/users/lookup.json"
    Public Const TWITTER_HOME_TIMELINE_URL As String = "https://api.twitter.com/1.1/statuses/home_timeline.json"
    Public Const TWITTER_MENTIONS_URL As String = "https://api.twitter.com/1.1/statuses/mentions_timeline.json"
    Public Const TWITTER_RETRIEVE_DIRECT_MESSAGES_URL As String = "https://api.twitter.com/1.1/direct_messages.json"
    Public Const TWITTER_DIRECT_MESSAGES_SENT_URL As String = "https://api.twitter.com/1.1/direct_messages/sent.json"
    Public Const TWITTER_DIRECT_MESSAGE_SEND_UPDATE_URL As String = "https://api.twitter.com/1.1/direct_messages/new.json"
    Public Const TWITTER_SEARCH_URL As String = "https://api.twitter.com/1.1/search/tweets.json"
    Public Const TWITTER_USER_SEARCH_URL As String = "https://api.twitter.com/1.1/users/search.json"
    Public TWITTER_RETWEET_URL As String = "https://api.twitter.com/1.1/statuses/retweet/{0}.json"
    Public TWITTER_DELETE_URL As String = "https://api.twitter.com/1.1/statuses/destroy/{0}.json"
    Public Const TWITTER_DELETE_DMS_URL As String = "https://api.twitter.com/1.1/direct_messages/destroy.json"
    Public Const TWITTER_SEND_DM_URL As String = "https://api.twitter.com/1.1/direct_messages/new.json"
    Public Const TWITTER_LISTS_URL As String = "https://api.twitter.com/1.1/lists/list.json"
    Public Const TWITTER_LISTS_STATUSES_URL As String = "https://api.twitter.com/1.1/lists/statuses.json"
    Public Const TWITTER_FOLLOW_USER_URL As String = "https://api.twitter.com/1.1/friendships/create.json"
    Public Const TWITTER_ADD_USER_TO_LIST_URL As String = "https://api.twitter.com/1.1/lists/members/create_all.json"
    Public Const TWITTER_REMOVE_USER_FROM_LIST_URL As String = "https://api.twitter.com/1.1/lists/members/destroy.json"
    Public Const TWITTER_UNFOLLOW_USER_URL As String = "https://api.twitter.com/1.1/friendships/destroy.json"
    Public Const TWITTER_CREATE_FAVORITE_URL As String = "https://api.twitter.com/1.1/favorites/create.json"
    Public Const TWITTER_DESTROY_FAVORITE_URL As String = "https://api.twitter.com/1.1/favorites/destroy.json"
    Public Const TWITTER_RETWEETS_OF_ME_URL As String = "https://api.twitter.com/1.1/statuses/retweets_of_me.json"
    Public Const TWITTER_RETWEETER_IDS_URL As String = "https://api.twitter.com/1.1/statuses/retweeters/ids.json"
    Public Const TWITTER_PROTECTED_REQUEST_URL As String = "https://api.twitter.com/1.1/friendships/outgoing.json"
    Public Const TWITTER_STATUS_LOOKUP_URL As String = "https://api.twitter.com/1.1/statuses/show.json"
    Public Const TWITTER_CREATE_LIST_URL As String = "https://api.twitter.com/1.1/lists/create.json"
    Public Const TWITTER_DELETE_LIST_URL As String = "https://api.twitter.com/1.1/lists/destroy.json"
    Public Const TWITTER_OWNED_LISTS_BY_USER_URL As String = "https://api.twitter.com/1.1/lists/ownerships.json"
    Public Const TWITTER_BLOCK_USER_URL As String = "https://api.twitter.com/1.1/blocks/create.json"
    Public Const TWITTER_UNBLOCK_USER_URL As String = "https://api.twitter.com/1.1/blocks/destroy.json"
    Public Const TWITTER_GET_TREND_LOCATIONS_URL As String = "https://api.twitter.com/1.1/trends/available.json"
    Public Const TWITTER_GET_TRENDS_BY_LOCATION_URL As String = "https://api.twitter.com/1.1/trends/place.json"


End Module